apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: cnb-example
spec:
  serviceAccountName: builder
  source:
    git:
      url: https://github.com/buildpack/sample-java-app.git
      revision: master
  template:
    name: buildpacks-cnb
    arguments:
    - name: IMAGE
      value: gcr.io/knative-test-244411/simple-app