---
apiVersion: v1
data:
  password: <GCP_SA_PASSWORD>
  username: <GCP_SA_USERNAME>
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: https://gcr.io
  name: gcr-creds-tkn
  namespace: default
type: kubernetes.io/basic-auth

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder-tkn
  namespace: default
secrets:
- name: gcr-creds-tkn

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-role
rules:
- apiGroups: ["serving.knative.dev"]
  resources: ["services"]
  verbs: ["get", "create", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-role
subjects:
- kind: ServiceAccount
  name: builder-tkn
