apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: sample-app
#  namespace: tekton-build
spec:
  type: image
  params:
    - name: url
      value: gcr.io/knative-test-244411/simple-app
