apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: cnb-example-kaniko
spec:
  serviceAccountName: builder-ssh
  source:
    git:
      url: git@github.com:ContainerSolutions/event-driven-kubernetes-workload.git
      revision: prepo_feature
  template:
    name: buildpacks-kaniko
    arguments:
    - name: IMAGE
      value: gcr.io/knative-test-244411/hello-world
    - name: BUILDER_IMAGE
      value: gcr.io/kaniko-project/executor:v0.6.0
    - name: PATH
      value: Dockerfile